### PR TITLE
Allow click on all the post box area

### PR DESCRIPTION
**Pull request by WennderSantos**
With a larger click area, it is easier to enter a post.

### CODE REVIEW

**Comment by WennderSantos** [comment]
@willianjusten  No?

**Comment by willianjusten** [comment]
Oh sorry, I'm very busy at the moment, that's why I didn't see this PR...
I think it's interesting, but maybe we can use another approach instead of javascript inline...

**Comment by WennderSantos** [comment]
@willianjusten Better? :)

**Comment by willianjusten** [comment]
Looks better to me =)

**Pull request merged**
